### ISSUE TITLE
So Close....

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/msteams-sharing-jetpack#1]
I'm having trouble with the final pieces of getting this plugin up and running. 

It's supposed to add a Microsoft Teams button in the Sharing Menu in Jetpack.

It's based on these two plugins, that enable the same functionality for their respective services: 

https://github.com/jeherve/scoopit-for-jetpack/
https://github.com/jeherve/vk-sharing-jetpack/

There is a functionality baked into Jetpack to allow users to add their own external services. This article talks a bit about how to  use it for Teams, but basically you need two URLs. The sharing URL and a link to a .png. 

In that instance, the URL he uses to trigger the share is:

`https://teams.microsoft.com/share?href=%post_url% `

using the %post_url% token available from the Jetpack interface. 

I'm trying to do the same thing with this link: 

```
return '<a target="_blank" rel="nofollow" class="share-msteams sd-button share-icon" href="https://teams.microsoft.com/share?href='. get_permalink( $post->ID ) .'"><span>Microsoft Teams</span></a>';
```
From here: 

https://github.com/hwdsb/msteams-sharing-jetpack/blob/558b9000a7dc0a4abad65bcbc4460aeacfd0cad8/class.teams-sharing-jetpack.php#L49-L60

Everything looks like the other two plugins, with some tweaks I thought would do the trick, but the plugin isn't working. 

Here's the docs from Microsoft referencing their share URL:

https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams

@r-a-y if you have a moment can you take a look. I think it's something that will probably be obvious to you. I thought about ripping out the "smart" call from this line to simplify things further: 

https://github.com/hwdsb/msteams-sharing-jetpack/blob/558b9000a7dc0a4abad65bcbc4460aeacfd0cad8/class.teams-sharing-jetpack.php#L10

And then again when it's called below. Let me know if I'm making any sense.

**Comment by r-a-y** [comment]
You almost got it, but your filename was wrong so your button couldn't properly render!

**Comment by mrjarbenne** [comment]
🤦🏻‍♂️
